server:
  port: 8014

documentation:
  baseurl: http://localhost
  swagger:
    services:
      - name: auth
        url: ${documentation.baseurl}:8080/v3/api-docs/Auth
        version: 2.0
      - name: notification
        url: ${documentation.baseurl}:8081/v3/api-docs/Notification
        version: 1.0
      - name: notificationV2
        url: ${documentation.baseurl}:8081/v3/api-docs/Notification%20V2
        version: 2.0

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /api/swagger-ui.html
    enabled: true



